baseurl = "https://maccroofing.github.io"
languageCode = "en-us"
title = "MACC Roofing"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Your name"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "MACC Roofing"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "MACC Roofing"
		subtitle   = "The Albany & New York Capital Region Roofing Experts."
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "We've got what you need!"
		description = "MACC Roofing provides a multitude of construction services that include Roofing, Siding, Paintiing, Gutters, Windows, and more for the interior & exterior of your home or business."
		buttonText  = "Contact Us Today!"


	# Service section
	[params.services]
		headline = "Services Provided"

        [[params.services.list]]
            icon = "fa-home"
            title = "Home Roofing"
            description = "Modern design and development that breathes life into new or old home."

        [[params.services.list]]
			icon = "fa-building-o"
			title = "Commercial Roofing"
			description = "Code enforced installation for any commercial building."

        [[params.services.list]]
            icon = "fa-plus"
            title = "Plus More"
            description = "Exterior & Interior services including gutters, siding, windows, and painting."

		[[params.services.list]]
            icon = "fa-thumbs-up "
            title = "Quality"
            description = "We do it right the first time!  Practicing top-quality construction standards."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	#[params.aside]
	#	headline = "Get the Creative Theme for Hugo"

	#	[params.aside.button]
	#		text = "Download now"
	#		link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Need an estimate? We can provide one! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = " 518-331-4488"
		email = "MACCRoofing518@gmail.com"

	 #Google Maps section
	[params.location]
	 	latitude  = "42.68530699999999"
	 	longitude = "-73.79656899999998"
	 	maps_api_key = "AIzaSyAe4_9zXYZkCLi-n6ieYyPpSMYG7-YvCtc"
